export const CATEGORIES_ACTION_TYPES = {
    // SET_CATEGORIES: 'SET_CATEGORIES'
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR'

}